### ISSUE TITLE
Parse YAML header in Markdown

### ISSUE THREAD

**Issue by Shreyas-21** [tarides/olinkcheck#53]
Add a `--with-yaml-header` flag to be used only with the `md` format.

**Comment by Shreyas-21** [comment]
The YAML header in the md files in ocaml.org follow a schema, with a `url` field which is hyperlinked.
The current YAML backend will look for URLs within strings and may ignore any surrounding characters.
Do we want to respect the schema and look for a `url` field and check whatever string that has, or keep it generic?
Following the schema might help in catching bugs like https://github.com/ocaml/ocaml.org/issues/1330

**Comment by cuihtlauac** [comment]
I can't see any reason not to respect the schema

**Comment by Shreyas-21** [comment]
It is inconsistent across the different files. For example, the `books` have a link in `uri`. The existing schemas can be inferred manually, but any new schema added in the future has to be accounted.

**Comment by cuihtlauac** [comment]
How many different case do we have?

**Comment by Shreyas-21** [comment]
Links may appear with the following keys: `url`, `uri`, `online_resource`, `preview_image`, `link`, `video` from what I've seen.
